server:
  port: 7071
spring:
  security:
    user:
      name: java10
      password: 123

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/socialAuth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${java10secretkey}
  issuer: ${java10issuer}

rabbitmq:
  auth-exchange: auth-exchange
  register-binding-key: register-key
  register-queue: register-queue
  activation-queue: queue-activation
  activation-binding-key: activation-key
  mail-queue: queue-mail
  mail-binding-key: mail-key
redis:
  host: localhost
  port: 6379
feign:
  user: http://localhost:7072/api/v1/user